### PR TITLE
Change `EmailAddressParser` to support addresses violating the specification

### LINKED ISSUE #6980: IMAP folders are empty
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.705

### Where did you get the app from?

Google Play

### Android version

13

### Device model

OnePlus 8 pro

### Steps to reproduce

Go to folder in IMAP account and open it. No mails are visible.

### Expected behavior

Mails should be visible. The folder isn't empty. There are 230 unread Mails indicated.

### Actual behavior

Some folders are empty. But not all of them. Interesting thing: If you use the search function the mails found get visible. If you delete the searched word the folder is shown as empty again.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/11738784/k9mail-logs.txt)

### PR DESCRIPTION
**Pull request by cketti**
Steps to test:
1. Run a debug build
2. Add an account for `demo@k9mail.example` (contains a message with an email address where the local part exceeds the 64 character limit)
3. Enable *Settings → General settings → Display → Show contact names*
4. Loading the message list for the inbox fails without this change and should load fine with this change applied.

Fixes #6980

### CODE REVIEW

File: core/common/src/main/kotlin/app/k9mail/core/common/mail/EmailAddressParserConfig.kt [hunk 1]
```diff
@@ -3,39 +3,63 @@ package app.k9mail.core.common.mail
...
+
+        /**
+         * This only allows a subset of valid email addresses. Use this when validating the email address a user wants
+         * to add to an account/identity.
          */
-        val DEFAULT = EmailAddressParserConfig(
-            allowQuotedLocalPart = true,
-            allowLocalPartRequiringQuotedString = true,
-            allowEmptyLocalPart = false,
+        val LIMITED = EmailAddressParserConfig(
```
Comment (wmontwe) [inline core/common/src/main/kotlin/app/k9mail/core/common/mail/EmailAddressParserConfig.kt:57]: I think this could be named `STRICT`, limited sounds like reduced funtionality

**Review by wmontwe — APPROVED** [review]
LGTM

File: core/common/src/main/kotlin/app/k9mail/core/common/mail/EmailAddressParserConfig.kt (hunk 1 above)
Comment (cketti) [reply core/common/src/main/kotlin/app/k9mail/core/common/mail/EmailAddressParserConfig.kt:57]: It kind of is, because we don't allow email addresses with a quoted local part, e.g. `"foo bar"@domain.example`.
